import { ms } from '@/shared/utils/scale';

import type { AppTheme } from './light';

export const darkTheme: AppTheme = {
  colors: {
    primary: '#52B788',
    primaryLight: '#74C69D',
    primaryDark: '#2D6A4F',
    secondary: '#F4CC45',
    secondaryLight: '#FFE57F',
    background: '#121212',
    surface: '#1E1E1E',
    surfaceElevated: '#2A2A2A',
    border: '#333333',
    text: '#EDEDED',
    textSecondary: '#A0A0A0',
    textTertiary: '#666666',
    textInverse: '#121212',
    error: '#EF5350',
    errorLight: '#3E2723',
    success: '#66BB6A',
    successLight: '#1B3E20',
    warning: '#FFA726',
    warningLight: '#3E2E1B',
    info: '#29B6F6',
    infoLight: '#1B2E3E',
    backdrop: 'rgba(0, 0, 0, 0.7)',
    overlay: 'rgba(0, 0, 0, 0.6)',
    barStyle: 'light-content' as const,
    tabBarBackground: '#1E1E1E',
  },
  fonts: {
    regular: 'OpenSans-Regular',
    semiBold: 'OpenSans-Semibold',
    bold: 'OpenSans-Bold',
    italic: 'OpenSans-Italic',
  },
  spacing: {
    xs: ms(4),
    sm: ms(8),
    md: ms(16),
    lg: ms(24),
    xl: ms(32),
    xxl: ms(48),
  },
  radius: {
    sm: ms(6),
    md: ms(12),
    lg: ms(16),
    xl: ms(24),
    full: 9999,
  },
  shadows: {
    sm: '0 1px 3px rgba(0, 0, 0, 0.3)',
    md: '0 2px 8px rgba(0, 0, 0, 0.4)',
    lg: '0 4px 16px rgba(0, 0, 0, 0.5)',
  },
  typography: {
    h1: { fontFamily: 'OpenSans-Bold', fontSize: ms(26), lineHeight: ms(34) },
    h2: { fontFamily: 'OpenSans-Bold', fontSize: ms(20), lineHeight: ms(28) },
    h3: { fontFamily: 'OpenSans-Semibold', fontSize: ms(17), lineHeight: ms(24) },
    body: { fontFamily: 'OpenSans-Regular', fontSize: ms(14), lineHeight: ms(20) },
    bodySmall: { fontFamily: 'OpenSans-Regular', fontSize: ms(12), lineHeight: ms(18) },
    caption: { fontFamily: 'OpenSans-Regular', fontSize: ms(11), lineHeight: ms(15) },
    label: { fontFamily: 'OpenSans-Semibold', fontSize: ms(13), lineHeight: ms(18) },
    button: { fontFamily: 'OpenSans-Bold', fontSize: ms(15), lineHeight: ms(20) },
  },
};
