import { ms } from '@/shared/utils/scale';

export const lightTheme = {
  colors: {
    primary: '#2D6A4F',
    primaryLight: '#52B788',
    primaryDark: '#1B4332',
    secondary: '#D4A017',
    secondaryLight: '#F4CC45',
    background: '#FAFAF8',
    surface: '#FFFFFF',
    surfaceElevated: '#F0EDE8',
    border: '#E0DDD8',
    text: '#1A1A1A',
    textSecondary: '#6B6B6B',
    textTertiary: '#9E9E9E',
    textInverse: '#FFFFFF',
    error: '#D32F2F',
    errorLight: '#FFEBEE',
    success: '#388E3C',
    successLight: '#E8F5E9',
    warning: '#F57C00',
    warningLight: '#FFF3E0',
    info: '#0288D1',
    infoLight: '#E1F5FE',
    backdrop: 'rgba(0, 0, 0, 0.5)',
    overlay: 'rgba(0, 0, 0, 0.4)',
    barStyle: 'dark-content' as 'dark-content' | 'light-content',
    tabBarBackground: '#FFFFFF',
  },
  fonts: {
    regular: 'OpenSans-Regular',
    semiBold: 'OpenSans-Semibold',
    bold: 'OpenSans-Bold',
    italic: 'OpenSans-Italic',
  },
  spacing: {
    xs: ms(4),
    sm: ms(8),
    md: ms(16),
    lg: ms(24),
    xl: ms(32),
    xxl: ms(48),
  },
  radius: {
    sm: ms(6),
    md: ms(12),
    lg: ms(16),
    xl: ms(24),
    full: 9999,
  },
  shadows: {
    sm: '0 1px 3px rgba(0, 0, 0, 0.05)',
    md: '0 2px 8px rgba(0, 0, 0, 0.08)',
    lg: '0 4px 16px rgba(0, 0, 0, 0.12)',
  },
  typography: {
    h1: { fontFamily: 'OpenSans-Bold', fontSize: ms(26), lineHeight: ms(34) },
    h2: { fontFamily: 'OpenSans-Bold', fontSize: ms(20), lineHeight: ms(28) },
    h3: { fontFamily: 'OpenSans-Semibold', fontSize: ms(17), lineHeight: ms(24) },
    body: { fontFamily: 'OpenSans-Regular', fontSize: ms(14), lineHeight: ms(20) },
    bodySmall: { fontFamily: 'OpenSans-Regular', fontSize: ms(12), lineHeight: ms(18) },
    caption: { fontFamily: 'OpenSans-Regular', fontSize: ms(11), lineHeight: ms(15) },
    label: { fontFamily: 'OpenSans-Semibold', fontSize: ms(13), lineHeight: ms(18) },
    button: { fontFamily: 'OpenSans-Bold', fontSize: ms(15), lineHeight: ms(20) },
  },
};

export type AppTheme = typeof lightTheme;
