export const lightTheme = {
  colors: {
    primary: '#2D6A4F',
    primaryLight: '#52B788',
    primaryDark: '#1B4332',
    secondary: '#D4A017',
    secondaryLight: '#F4CC45',
    background: '#FAFAF8',
    surface: '#FFFFFF',
    surfaceElevated: '#F0EDE8',
    border: '#E0DDD8',
    text: '#1A1A1A',
    textSecondary: '#6B6B6B',
    textTertiary: '#9E9E9E',
    textInverse: '#FFFFFF',
    error: '#D32F2F',
    errorLight: '#FFEBEE',
    success: '#388E3C',
    successLight: '#E8F5E9',
    warning: '#F57C00',
    warningLight: '#FFF3E0',
    info: '#0288D1',
    infoLight: '#E1F5FE',
    barStyle: 'dark-content' as 'dark-content' | 'light-content',
    tabBarBackground: '#FFFFFF',
    cardShadow: 'rgba(0,0,0,0.08)',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  radius: {
    sm: 6,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
  typography: {
    h1: { fontSize: 28, fontWeight: '700' as const, lineHeight: 36 },
    h2: { fontSize: 22, fontWeight: '600' as const, lineHeight: 30 },
    h3: { fontSize: 18, fontWeight: '600' as const, lineHeight: 26 },
    body: { fontSize: 15, fontWeight: '400' as const, lineHeight: 22 },
    bodySmall: { fontSize: 13, fontWeight: '400' as const, lineHeight: 20 },
    caption: { fontSize: 11, fontWeight: '400' as const, lineHeight: 16 },
    label: { fontSize: 13, fontWeight: '500' as const, lineHeight: 18 },
    button: { fontSize: 15, fontWeight: '600' as const, lineHeight: 22 },
  },
};

export type AppTheme = typeof lightTheme;
